$HOME/.config/hypr/themes/theme.conf|> $HOME/.config/hypr/themes/colors.conf

$GTK_THEME = Sweet-Dark
$ICON_THEME = candy-icons
$COLOR_SCHEME=prefer-dark
$CURSOR_THEME = Sweet-cursors
$CURSOR_SIZE=20
$CODE_THEME=Modern Purple Theme Dark

exec = gsettings set org.gnome.desktop.interface icon-theme '$ICON_THEME'
exec = gsettings set org.gnome.desktop.interface gtk-theme '$GTK_THEME'
exec = gsettings set org.gnome.desktop.interface color-scheme '$COLOR_SCHEME'
exec = Hyde cursor theme '$CURSOR_THEME' size $CURSOR_SIZE
exec = Hyde code theme '$CODE_THEME'

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(c74dedff) rgba(ed254eff) 45deg
    col.inactive_border = rgba(00c1e4cc) rgba(7cb7ffcc) 45deg
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(c74dedff) rgba(ed254eff) 45deg
    col.border_inactive = rgba(00c1e4cc) rgba(7cb7ffcc) 45deg
    col.border_locked_active = rgba(c74dedff) rgba(ed254eff) 45deg
    col.border_locked_inactive = rgba(00c1e4cc) rgba(7cb7ffcc) 45deg
}

decoration {
    rounding = 10

    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }

    shadow {
        enabled = false
    }
}
